name: Ghost Absen Schedule

on:
  schedule:
    # --- ABSEN PAGI (06:40 - 07:55 WITA) ---
    # Jam 22:45 UTC = 06:45 WITA (Senin - Jumat)
    - cron: '45 22 * * 0-4'
    
    # --- ABSEN SORE (16:30 - 18:00 WITA) ---
    # Jam 08:40 UTC = 16:40 WITA (Senin - Jumat)
    - cron: '40 8 * * 1-5'
    
    # Cadangan Sore jam 09:30 UTC = 17:30 WITA
    - cron: '30 9 * * 1-5'
    
  workflow_dispatch:

jobs:
  absen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run Engine
        run: python engine.py
